<?php 

namespace Valium\PT;

/**
 * Validates an array of NIB numbers for the Portuguese market.
 * Also retrieves bank names and other information related to NIB and IBAN codes.
 *
 * @since  1.2.0
 * @author  WP Helpers | Carlos Matos
 */
class Iban
{
	/**
	 * Letter swapping according to IBAN's algorithm.
	 * @var $swaps
	 * @since  1.2.0
	 */
	protected $letters = ['A',  'B',  'C',  'D',  'E',  'F',  'G',  'H',  'I',  'J',  'K',  'L',  'M', 'N',  'O',  'P',  'Q',  'R',  'S',  'T',  'U',  'V',  'W',  'X',  'Y',  'Z'];

	protected $converted = ['10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35'];

	protected $banks = [
		'0001' => 'BANCO DE PORTUGAL, EP',
		'0005' => 'ABANCA SERVICIOS FINANCIEROS, E.F.C., S.A.- SUCURSAL EM PORTUGAL',
		'0007' => 'NOVO BANCO, SA',
		'0008' => 'BANCO BAI EUROPA, SA',
		'0010' => 'BANCO BPI, SA',
		'0014' => 'BANCO INVEST, SA',
		'0018' => 'BANCO SANTANDER TOTTA, SA',
		'0019' => 'BANCO BILBAO VIZCAYA  ARGENTARIA, S.A. - SUCURSAL EM PORTUGAL',
		'0022' => 'BANCO DO BRASIL AG - SUCURSAL EM PORTUGAL',
		'0023' => 'BANCO ACTIVOBANK, SA',
		'0025' => 'CAIXA - BANCO DE INVESTIMENTO, SA',
		'0032' => 'BARCLAYS BANK IRELAND PLC - SUCURSAL EM PORTUGAL',
		'0033' => 'BANCO COMERCIAL PORTUGUÊS, SA',
		'0034' => 'BNP PARIBAS',
		'0035' => 'CAIXA GERAL DE DEPÓSITOS, SA',
		'0036' => 'CAIXA ECONÓMICA MONTEPIO GERAL, CAIXA ECONÓMICA BANCÁRIA, SA',
		'0043' => 'DEUTSCHE BANK AKTIENGESELLSCHAFT - SUCURSAL EM PORTUGAL',
		'0045' => 'CAIXA DE CRÉDITO AGRÍCOLA, CRL',
		'1020' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE AROUCA, CRL',
		'1280' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO MÉDIO AVE, CRL',
		'1290' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE VILA VERDE E DE TERRAS DO BOURO, CRL',
		'1320' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE TERRAS DO SOUSA, AVE, BASTO E TÂMEGA, CRL',
		'1340' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO VALE DO SOUSA E BAIXO TÂMEGA, CRL',
		'1400' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE PAREDES, CRL',
		'1420' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO NOROESTE, CRL',
		'1440' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA ÁREA METROPOLITANA DO PORTO, CRL',
		'1460' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE PÓVOA DE VARZIM,VILA DO CONDE E ESPOSENDE, CRL',
		'1470' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO ALTO CÁVADO E BASTO, CRL',
		'2040' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO ALTO DOURO, CRL',
		'2090' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO BEIRA DOURO E LAFÕES, CRL',
		'2140' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO DOURO E CÔA, CRL',
		'2160' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO VALE DO TÁVORA E DOURO, CRL',
		'2190' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA TERRA QUENTE, CRL',
		'2230' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE TRÁS-OS-MONTES E ALTO DOURO, C.R.L.',
		'2260' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DOURO E SABOR, CRL',
		'3010' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO BAIXO MONDEGO, CRL',
		'3020' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE CANTANHEDE E MIRA, CRL',
		'3030' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE COIMBRA, CRL',
		'3060' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO VALE DO DÃO E ALTO VOUGA, CRL',
		'3090' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE OLIVEIRA DE AZEMÉIS E ESTARREJA, CRL',
		'3110' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE POMBAL, CRL',
		'3160' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE VALE DE CAMBRA, CRL',
		'3210' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE OLIVEIRA DO BAIRRO, CRL',
		'3220' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA COSTA VERDE, CRL',
		'3240' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO BAIXO VOUGA, CRL',
		'3310' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALBERGARIA E SEVER, CRL',
		'3340' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE VAGOS, CRL',
		'3370' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DAS SERRAS DE ANSIÃO, CRL',
		'3380' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE OLIVEIRA DO HOSPITAL, CRL',
		'3400' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA BAIRRADA E AGUIEIRA, CRL',
		'3450' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO BEIRA CENTRO, CRL',
		'3470' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE TERRAS DE VIRIATO, CRL',
		'4020' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA REGIÃO DO FUNDÃO E SABUGAL, CRL',
		'4050' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA BEIRA BAIXA (SUL), CRL',
		'4080' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA SERRA DA ESTRELA, CRL',
		'4110' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA ZONA DO PINHAL, CRL',
		'5020' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALCOBAÇA, CARTAXO, NAZARÉ, RIO MAIOR E SANTARÉM, CRL',
		'5050' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALENQUER, CRL',
		'5060' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ARRUDA DOS VINHOS, CRL',
		'5070' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE AZAMBUJA, CRL',
		'5080' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA BATALHA, CRL',
		'5120' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE CADAVAL, CRL',
		'5130' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE CALDAS DA RAINHA, ÓBIDOS E PENICHE, CRL',
		'5140' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE LOURES, SINTRA E LITORAL, CRL',
		'5170' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE CORUCHE, CRL',
		'5190' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE LOURINHÃ, CRL',
		'5230' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE PERNES E ALCANHÕES, CRL',
		'5240' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE PORTO DE MÓS, CRL',
		'5270' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE SALVATERRA DE MAGOS, CRL',
		'5310' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE SOBRAL DE MONTE AGRAÇO, CRL',
		'5360' => 'CAIXA DE CREDITO AGRICOLA MUTUO DE VILA FRANCA DE XIRA, CRL',
		'5430' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO RIBATEJO NORTE E TRAMAGAL, CRL',
		'5460' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ENTRE TEJO E SADO, CRL',
		'5470' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO RIBATEJO SUL, CRL',
		'6020' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALCÁCER DO SAL E MONTEMOR-O-NOVO, CRL',
		'6040' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALJUSTREL E ALMODÔVAR, CRL',
		'6100' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO ALENTEJO SUL, CRL',
		'6110' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE BORBA, CRL',
		'6150' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO NORDESTE ALENTEJANO, CRL',
		'6160' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ELVAS E CAMPO MAIOR, CRL',
		'6170' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ESTREMOZ, MONFORTE E ARRONCHES, CRL',
		'6240' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE MORAVIS, CRL',
		'6250' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO GUADIANA INTERIOR, CRL',
		'6320' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA COSTA AZUL, CRL',
		'6330' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE SÃO TEOTÓNIO, CRL',
		'6430' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO NORTE ALENTEJANO, CRL',
		'6440' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO ALENTEJO CENTRAL, CRL',
		'7010' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE ALBUFEIRA, CRL',
		'7120' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE SÃO BARTOLOMEU DE MESSINES E SÃO MARCOS DA SERRA, CRL',
		'7130' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE SILVES, CRL',
		'7140' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO SOTAVENTO ALGARVIO, CRL',
		'7210' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DO ALGARVE, CRL',
		'8050' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DOS AÇORES, CRL',
		'9000' => 'CAIXA CENTRAL - CAIXA CENTRAL DE CRÉDITO AGRÍCOLA MÚTUO, CRL',
		'0047' => 'HAITONG BANK, SA',
		'0048' => 'BANCO FINANTIA, SA',
		'0057' => 'CAIXA ECONÓMICA DO PORTO',
		'0059' => 'CAIXA ECONÓMICA DA MISERICÓRDIA DE ANGRA DO HEROÍSMO, CAIXA ECONÓMICA BANCÁRIA, SA',
		'0060' => 'BANCO MADESANT - SOCIEDADE UNIPESSOAL, SA',
		'0061' => 'BANCO DE INVESTIMENTO GLOBAL, SA',
		'0063' => 'BISON BANK, S.A.',
		'0064' => 'BANCO PORTUGUÊS DE GESTÃO, SA',
		'0065' => 'BEST - BANCO ELECTRÓNICO DE SERVIÇO TOTAL, SA',
		'0073' => 'BANCO SANTANDER CONSUMER PORTUGAL, SA',
		'0076' => 'MONTEPIO INVESTIMENTO, SA',
		'0079' => 'BANCO BIC PORTUGUÊS, SA',
		'0082' => 'FCE BANK PLC',
		'0086' => 'BANCO EFISA, SA',
		'0097' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DA CHAMUSCA, CRL',
		'0098' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE BOMBARRAL, CRL',
		'0160' => 'NOVO BANCO DOS AÇORES, SA',
		'0169' => 'CITIBANK EUROPE PLC - SUCURSAL EM PORTUGAL',
		'0170' => 'ABANCA CORPORACION BANCARIA, SA - SUCURSAL EM PORTUGAL',
		'0171' => 'RCI BANQUE - SUCURSAL PORTUGAL',
		'0172' => 'BMW BANK GMBH - SUCURSAL PORTUGUESA',
		'0173' => 'EDMOND DE ROTHSCHILD EUROPE - SUCURSAL EM PORTUGAL',
		'0189' => 'BANCO ATLÂNTICO EUROPA, SA',
		'0191' => 'BNI - BANCO DE NEGÓCIOS INTERNACIONAL (EUROPA), SA',
		'0193' => 'BANCO CTT, SA',
		'0195' => 'ITAÚ BBA EUROPE, S.A.',
		'0235' => 'BANCO L.J. CARREGOSA, SA',
		'0238' => 'BNP PARIBAS LEASE GROUP, SA',
		'0246' => 'BANCO PRIMUS, SA',
		'0257' => 'BNP PARIBAS SECURITIES SERVICES - SUCURSAL EM PORTUGAL',
		'0259' => 'DE LAGE LANDEN INTERNATIONAL, B.V. - SUCURSAL EM PORTUGAL',
		'0264' => 'VOLKSWAGEN BANK GMBH - SUCURSAL EM PORTUGAL',
		'0266' => 'BANK OF CHINA (LUXEMBOURG), SA LISBON BRANCH - SUCURSAL EM PORTUGAL',
		'0267' => 'CREDIT SUISSE (LUXEMBOURG), SA - SUCURSAL EM PORTUGAL',
		'0269' => 'BANKINTER, SA - SUCURSAL EM PORTUGAL',
		'0270' => 'IBM DEUTSCHLAND KREDITBANK GMBH - SUCURSAL EM PORTUGAL',
		'0271' => 'TOYOTA KREDITBANK GMBH – SUCURSAL EM PORTUGAL',
		'0272' => 'WIZINK BANK, SA - SUCURSAL EM PORTUGAL',
		'0274' => 'CECABANK, SA - SUCURSAL EM PORTUGAL',
		'0275' => 'BANCO SABADELL, SA - SUCURSAL EM PORTUGAL',
		'0276' => 'BANCA FARMAFACTORING SPA - SUCURSAL EM PORTUGAL',
		'0277' => 'CAIXABANK,S.A.  - SUCURSAL EM PORTUGAL',
		'0278' => 'GRENKE BANK AG - SUCURSAL EM PORTUGAL',
		'0280' => 'EFG BANK (LUXEMBOURG) S.A. - SUCURSAL EM PORTUGAL',
		'0305' => '321 CRÉDITO - INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0314' => 'SOFID - SOCIEDADE PARA O FINANCIAMENTO DO DESENVOLVIMENTO, INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0329' => 'REALTRANSFER - INSTITUIÇÃO DE PAGAMENTOS, SA',
		'0500' => 'ING BANK NV - SUCURSAL EM PORTUGAL',
		'0698' => 'UNICRE - INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0771' => 'CREDIT AGRICOLE LEASING & FACTORING - SUCURSAL EM PORTUGAL',
		'0780' => 'FCA CAPITAL PORTUGAL, INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0781' => 'AGENCIA DE GESTAO DA TESOURARIA E DA DIVIDA PUBLICA - IGCP, E.P.E.',
		'0796' => 'MONTEPIO CRÉDITO - INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0800' => 'BBVA, INSTITUIÇÃO FINANCEIRA DE CRÉDITO, SA',
		'0812' => 'NOVACÂMBIOS - INSTITUIÇÃO DE PAGAMENTO, SA',
		'0824' => 'UNICÂMBIO - INSTITUIÇÃO DE PAGAMENTO, SA',
		'0848' => 'BNP PARIBAS PERSONAL FINANCE, S.A. - SUCURSAL EM PORTUGAL',
		'0881' => 'ONEY BANK - SUCURSAL EM PORTUGAL',
		'0916' => 'BANCO CREDIBOM, SA',
		'0921' => 'COFIDIS',
		'0955' => 'OREY FINANCIAL - INSTITUICAO FINANCEIRA DE CREDITO, SA',
		'5180' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE LEIRIA, CRL',
		'5200' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE MAFRA, CRL',
		'5340' => 'CAIXA DE CRÉDITO AGRÍCOLA MÚTUO DE TORRES VEDRAS, CRL',
		'7500' => 'SFS – FINANCIAL SERVICES, IME, S.A.',
		'7837' => 'VIVA PAYMENT SERVICES SA',
		'8115' => 'CTT - CORREIOS DE PORTUGAL, SA',
		'8700' => 'LUSOPAY, INSTITUIÇÃO DE PAGAMENTO, LDA',
		'8701' => 'PAYSHOP (PORTUGAL), SA',
		'8703' => 'SIBS PAGAMENTOS, SA',
		'8705' => 'ALTICE PAY, SA',
		'8706' => 'EASYPAY - INSTITUIÇÃO DE PAGAMENTO, LDA',
		'8707' => 'IFTHENPAY, LDA',
		'8708' => 'MAXPAY - INSTITUIÇÃO DE PAGAMENTO, LDA',
		'8709' => 'EUPAGO - INSTITUIÇÃO DE PAGAMENTO, LDA',
		'8710' => 'PAYPAYUE - INSTITUIÇÃO DE PAGAMENTO, UNIPESSOAL, LDA',
		'8711' => 'RAIZE - INSTITUIÇÃO DE PAGAMENTOS, SA',
		'8863' => 'MONTY GLOBAL PAYMENTS, S.A.',
		'8987' => 'LUFTHANSA AIRPLUS SERVICEKARTEN GMBH - SUCURSAL EM PORTUGAL',
	];

	public function check(array $codes)
	{
		$results = [];

		foreach($codes as $code) {
			$results[$code] = $this->validate($code);
		}

		return $results;
	}

	public function validate(string $string)
	{
		$string = strtoupper(str_replace(' ', '', $string));
        $string = substr($string, 4) . substr($string, 0, 4);

        $string = str_replace(
            $this->letters,
            $this->converted,
            $string
        );

        $process = 0;

        for ($i = 0; $i < strlen($string); $i++) {

            $process = $process * 10;
            $process = $process + intval(substr($string, $i, 1));
            $process = $process % 97;
        }

        if($process == 1) {
        	return true;
        } else {
        	return false;
        }

	}

	public function getBank(string $string)
	{
		$string = substr($string, 4, 4);

		return $this->banks[$string];
	}
}
